### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jeroenhoogland** [sunaku/glove80-keymaps#9]
The new v35 keycap gives a build error when disabling ENFORCE_BILATERAL (with qwerty layer first).
I'm unsure why since the definition referred to in the error is nicely captured in an #ifdef ENFORCE_BILATERAL.

In detail, after commenting out the line:

// #define ENFORCE_BILATERAL   // cancels single-handed home row mod+tap

The message in question is:

devicetree error: /keymap/layer_LeftPinky: undefined node label 'left_pinky_tap'

Full compile log:
Loading Zephyr default modules (Zephyr base (cached)).
-- Application: /nix/store/08q7fx9jd9r1wgsxc3vjdks9f9v4lwrz-source/app
-- CMake version: 3.27.8
-- Found Python3: /nix/store/qrrwy165fvfdxcp6yn01yjbi7fsn3zmf-python3-3.11.6-env/bin/python (found suitable version "3.11.6", minimum required is "3.8") found components: Interpreter 
-- Cache files will be written to: /tmp/.cache
-- Zephyr version: 3.5.0 (/nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr), build: 2fad527cc5abed5bb59b4d4a4b0ee511d0e514e9
-- Using keymap file: /tmp/build/build.keymap
-- Board: glove80_lh
-- Found toolchain: gnuarmemb (/nix/store/rfmw7rw1l85rvav1fymij2253w7vz070-ccache-links)
-- Found Dtc: /nix/store/vrigkjb8pzdc01ggppbfyh6mcnnv2lzw-dtc-1.7.0/bin/dtc (found suitable version "1.7.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /nix/store/08q7fx9jd9r1wgsxc3vjdks9f9v4lwrz-source/app/boards/arm/glove80/glove80_lh.dts
-- Found devicetree overlay: /tmp/build/build.keymap
devicetree error: /keymap/layer_LeftPinky: undefined node label 'left_pinky_tap'
-- In: /tmp/build/zephyr, command: /nix/store/qrrwy165fvfdxcp6yn01yjbi7fsn3zmf-python3-3.11.6-env/bin/python;/nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/scripts/dts/gen_defines.py;--dts;/tmp/build/zephyr/zephyr.dts.pre;--dtc-flags;'';--bindings-dirs;/nix/store/08q7fx9jd9r1wgsxc3vjdks9f9v4lwrz-source/app/module/dts/bindings;/nix/store/08q7fx9jd9r1wgsxc3vjdks9f9v4lwrz-source/app/dts/bindings;/nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/dts/bindings;--header-out;/tmp/build/zephyr/include/generated/devicetree_generated.h.new;--dts-out;/tmp/build/zephyr/zephyr.dts.new;--edt-pickle-out;/tmp/build/zephyr/edt.pickle;--vendor-prefixes;/nix/store/08q7fx9jd9r1wgsxc3vjdks9f9v4lwrz-source/app/dts/bindings/vendor-prefixes.txt;--vendor-prefixes;/nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/dts/bindings/vendor-prefixes.txt
CMake Error at /nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/cmake/modules/dts.cmake:279 (message):
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
  /nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)
  CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by sunaku** [comment]
Thanks for reporting this bug.  It's a known issue in v35 that has been fixed in commit 34bbc831003cae7d2b55bd219f4306b84b06779c and will be released in v36.

**Comment by jeroenhoogland** [comment]
That's great! Thanks for squashing it, and most of all, thanks for the hard work on all the awesome features!

**Comment by sunaku** [comment]
Fix released in v36.

**Comment by kamskr** [comment]
I still experience a build issue on the newest v36. Everything works correctly when I build the default configuration, but as soon as I add any customisation i receive an error. I only added one parameter to the top of "Custom Defined Behaviors":

```
#define DIFFICULTY_LEVEL 4 // this is the only uncommented line I added to the top of Custom Defined Behaviors
//#define OPERATING_SYSTEM 'M'
//#define MOUSE_MOTION_MAXIMUM_SPEED 1800
//#define MOUSE_SCROLL_MAXIMUM_SPEED 30

// NOTE: Use the `#define` settings below to customize this keymap!
// For example, here are the main optional features you can enable:
...
```

Full error log for Firmware Verions community.pr23.mouse-keys:
```
Error: <stdin>:434.49-50 syntax error
FATAL ERROR: Unable to parse input tree
```

Full error log for Firmware Version v24.02:
```
devicetree error: /tmp/build/build.keymap:1872 (column 49): parse error: expected number or parenthesized expression

Full compile log:
Loading Zephyr default modules (Zephyr base (cached)).
-- Application: /nix/store/08q7fx9jd9r1wgsxc3vjdks9f9v4lwrz-source/app
-- CMake version: 3.27.8
-- Found Python3: /nix/store/qrrwy165fvfdxcp6yn01yjbi7fsn3zmf-python3-3.11.6-env/bin/python (found suitable version "3.11.6", minimum required is "3.8") found components: Interpreter 
-- Cache files will be written to: /tmp/.cache
-- Zephyr version: 3.5.0 (/nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr), build: 2fad527cc5abed5bb59b4d4a4b0ee511d0e514e9
-- Using keymap file: /tmp/build/build.keymap
-- Board: glove80_lh
-- Found toolchain: gnuarmemb (/nix/store/rfmw7rw1l85rvav1fymij2253w7vz070-ccache-links)
-- Found Dtc: /nix/store/vrigkjb8pzdc01ggppbfyh6mcnnv2lzw-dtc-1.7.0/bin/dtc (found suitable version "1.7.0", minimum required is "1.4.6") 
-- Found BOARD.dts: /nix/store/08q7fx9jd9r1wgsxc3vjdks9f9v4lwrz-source/app/boards/arm/glove80/glove80_lh.dts
-- Found devicetree overlay: /tmp/build/build.keymap
devicetree error: /tmp/build/build.keymap:1872 (column 49): parse error: expected number or parenthesized expression
-- In: /tmp/build/zephyr, command: /nix/store/qrrwy165fvfdxcp6yn01yjbi7fsn3zmf-python3-3.11.6-env/bin/python;/nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/scripts/dts/gen_defines.py;--dts;/tmp/build/zephyr/zephyr.dts.pre;--dtc-flags;'';--bindings-dirs;/nix/store/08q7fx9jd9r1wgsxc3vjdks9f9v4lwrz-source/app/module/dts/bindings;/nix/store/08q7fx9jd9r1wgsxc3vjdks9f9v4lwrz-source/app/dts/bindings;/nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/dts/bindings;--header-out;/tmp/build/zephyr/include/generated/devicetree_generated.h.new;--dts-out;/tmp/build/zephyr/zephyr.dts.new;--edt-pickle-out;/tmp/build/zephyr/edt.pickle;--vendor-prefixes;/nix/store/08q7fx9jd9r1wgsxc3vjdks9f9v4lwrz-source/app/dts/bindings/vendor-prefixes.txt;--vendor-prefixes;/nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/dts/bindings/vendor-prefixes.txt
CMake Error at /nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/cmake/modules/dts.cmake:279 (message):
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
  /nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /nix/store/6p8b3xwjz1w7vijrcysij2f17fn73492-zephyr/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)
  CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
```
